### ISSUE TITLE
Some buttons are no longer displayed after you select "Community Discussion Only" section [Search Pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#128]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2 In the search field type "cookies"
3. Select "Community Discussion Only" section

ER: The section is selected and the other 2 sections "Show Everything", "Help Articles Only" are still displayed and actionable. 
AR: The "Show Everything" and "Help Articles Only" sections are no longer displayed.

**Comment by kkellydesign** [comment]
From what I can tell, this is how it works in production as well, but it's tough to find because the index is so much larger in production. The issue that you're seeing is that there are no search results that match "cookie" in the community discussion forum, so that result is turning up the "no results" screen. The "no results" screen doesn't have the tab bar, because there's no sense in filtering "zero" results. The results that you are seeing in your community discussion tab here is the default list when no results are displayed, with the heading "We couldn't find any results for ‘cookies’ in ‘English’. Maybe one of these articles will be helpful?"

If you'd like to see this working properly, type the search term "outlook." There is a community discussion that matches that query, so you'll see all three tabs working correctly there.

**Comment by ovidiuboca1** [comment]
I understand your opinion, but the problem is when a user will search after a term that doesn't have any result in the "Community Discussion Only" section but this section will be displayed and the user will click on it(because is clickable even though it doesn't have any results)and it will be stuck there and it will not be possible to go back on the previous state. Also, it doesn't help you to click on the back button form the browser. The idea is that the user if will click on the "Community Discussion Only" section, will end up in a place that doesn't have any option to go back. Maybe if there are no results it will be a good idea to make that button unactionable.

**Comment by mirunacurtean** [comment]
Verified fixed across tests for #131, #169 and #714 .
