### ISSUE TITLE
The "Relevance" dropdown is missing [Search pages]

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#129]
STR:
1. Go to https://test.sumo.mozit.cloud/en-US/
2. Make a search after a keyword, use cookies

ER: In the right part of the page you see a dropdown and the "Relevance" is selected. See the expected result here https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5e189569853c8c01a6248a73
AR:  In the right part of the page the dropdown is missing.

**Comment by kkellydesign** [comment]
This is a new backend feature that is outside the scope of the current redesign project. @madasan or @akatsoulas, is there a good place to collect tickets like this? I think since it's on the roadmap to rebuild the search as a backend-only elasticsearch integration, that would be a good time to add this feature.

**Comment by akatsoulas** [comment]
For now we are not going to add functionality like this
