### ISSUE TITLE
"Help Articles Only" results are returned by default, cannot show all results

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/sumo-project#131]
**STR:**

1. Navigate to https://test.sumo.mozit.cloud/en-US/
2. Enter a keyword in the search input field (e.g: "Firefox")

**Expected:**
All search results are returned, filter is set to show everything

**Actual:**
Search results filtered by "Help Articles Only" are returned 

**Note:**
Tapping "Show everything" button has no effect, user is not able to get all results unfiltered.
See [video](https://drive.google.com/file/d/1RUoF4Chn0YVAC1cW81UI6Ismc4LF06hz/view?usp=sharing)

**Env:**
iPhone X, iOS 13.3, Chrome, Firefox and Safari

**Comment by kkellydesign** [comment]
I'm seeing this too, both locally, on the test server, and on the old codebase on production, so this is an issue with the current JS search implementation.

**Comment by mirunacurtean** [comment]
This ticket is updated due to the repro of the issue having changed. Also, it occurs on both mobile and desktop. 
New repro steps:
1. Perform a search using the keyword "keyword" and switch between "View All", "Help Articles Only" and "Community Discussions Only" sections. Notice that at this point this is done with no issues. 
2. Erase keyword and use new keyword " Firefox".
3. After the search results for Firefox is displayed select to filter results to see "Help Articles Only" and then by product category. select "Firefox Lite".  0 search results should be found. 
4. Change search keyword again to "keyword". 

**Actual results:**
Search results for keyword are displayed for the "Help Articles Only" section by default.  Trying to switch to "View All" yields no changes. 

![Cannot select View all on second search attempt](https://user-images.githubusercontent.com/53306802/98267557-32a18880-1f94-11eb-89f4-76eabf582352.gif)
NOTE that this does not occur if the page is refreshed between each search. 

**Expected results:**
At any time, when performing a search, with or without reloading the page, the user must be able to switch between the "View All", "Help Articles Only" and "Community Discussions Only" sections.

**Comment by mirunacurtean** [comment]
Verified fixed across Windows Firefox and Chrome and iOS/android on Firefox. No longer occurs, meaning the user is no longer stuck in the Help Articles section upon performing a new search. 
However, the previously selected section: "View All", Help Articles Only" or "Community Discussion only" and the filter by product selections are kept when performing a new search without refreshing the page. This looks to be expected. 

![no longer stuck in Help Articles](https://user-images.githubusercontent.com/53306802/108979424-4e3fb480-7693-11eb-9a72-7683d1af2db8.gif)
