### ISSUE TITLE
Responsive Redesign // UI-Design Edits

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#147]
@kkellydesign 

- spacing, increase across all breakpoints, especially in header areas.

- This 'Need more help' component. For now follow latest design as discussed -- ink-09 with metropolis -- instead of what is captured here below.
![Screen Shot 2020-01-30 at 1 02 20 PM](https://user-images.githubusercontent.com/54991698/73578251-2b6dad00-444d-11ea-8133-1c59758b6801.png)

- 'See All Products' link in the navigation, style like blue text link 
![Screen Shot 2020-01-30 at 1 03 45 PM](https://user-images.githubusercontent.com/54991698/73578319-59eb8800-444d-11ea-87e5-40331b83ed6f.png)

- Gravatar ?? lets try and round those corners and if you can figure out how to make the FxA avatar work instead then lets go with that (shown below)
![Screen Shot 2020-01-30 at 1 09 06 PM](https://user-images.githubusercontent.com/54991698/73578357-74bdfc80-444d-11ea-8ef7-a303bce2dc67.png)
![Img_avatar](https://user-images.githubusercontent.com/54991698/73578417-96b77f00-444d-11ea-887e-5def699b705a.png 

- Same with this on the profile editing, change this to upload/browse select your img or pencil icon on hover to edit photo ? Gravatar is weird hah.
![Screen Shot 2020-01-30 at 1 10 31 PM](https://user-images.githubusercontent.com/54991698/73578443-a636c800-444d-11ea-915b-a25008c46d27.png)

- Layouts with sidebar: sidebar sits on the right side, content sits to the left (needs to be switched in some pages ie. profile settings)
![Screen Shot 2020-01-30 at 1 13 01 PM](https://user-images.githubusercontent.com/54991698/73578635-1f361f80-444e-11ea-8c8f-bbac6d3d7610.png)

- Make the checkboxes bigger - matching the UI specificed in system on Zeplin component library/protocol.
![Screen Shot 2020-01-30 at 1 12 06 PM](https://user-images.githubusercontent.com/54991698/73578582-00378d80-444e-11ea-8444-aad6cb3758cf.png)

**Comment by kkellydesign** [comment]
@jess-cook03 This will be ready for another design pass when this is in: 
https://github.com/mozilla/kitsune/pull/4170

<img width="1410" alt="Screen Shot 2020-02-11 at 12 27 50 PM" src="https://user-images.githubusercontent.com/202590/74261974-0806f580-4cca-11ea-8056-a869c62feb58.png">

form macros have been added to allow custom checkboxes anywhere, and maintain consistency. Whenever possible, use this new pattern for forms instead of `{{ form.as_ul }}`

<img width="1286" alt="Screen Shot 2020-02-11 at 11 40 03 AM" src="https://user-images.githubusercontent.com/202590/74262385-c165cb00-4cca-11ea-95ff-29fc5266cb30.png">
<img width="582" alt="Screen Shot 2020-02-11 at 11 39 54 AM" src="https://user-images.githubusercontent.com/202590/74262394-c4f95200-4cca-11ea-86bd-8e33626d8060.png">
<img width="399" alt="Screen Shot 2020-02-11 at 10 53 00 AM" src="https://user-images.githubusercontent.com/202590/74262402-c88cd900-4cca-11ea-86c4-2ef31260cc80.png">

**Comment by jess-cook03** [comment]
@kkellydesign marked for review considering a few elements here overlap with edits needed in other tickets -- ie Forum / thread pages #67 and need more help component edits #179

**Comment by kkellydesign** [comment]
@jess-cook03 If there is nothing left that is actionable in this ticket, I think it's good to be closed, even if there are related tickets open elsewhere. At this point, I think smaller single-topic tickets are best. Moving back to QA for confirmation.

**Comment by jess-cook03** [comment]
Confirmed this is done
