### ISSUE TITLE
[Home Page] The size of the icons is smaller 

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#162]
CC @jess-cook03 @kkellydesign 

STR:

1. Go to https://test.sumo.mozit.cloud/en-US
2. Observe the size of the icons

ER: The size of the icons matches the one form spec: https://app.zeplin.io/project/5db3524d3cd0612c5d2f78a9/screen/5dd873054a74858ba790640d
AR: The size of the icons is smaller compared with the one from the spec.

**Comment by kkellydesign** [comment]
The images need re-uploaded into the database without whitespace around the logos. Check out this image on the production site: 

https://user-media-prod-cdn.itsre-sumo.mozilla.net/uploads/products/2019-10-21-15-00-41-7478b4.png

The new logos need to be around 160x160, give-or-take. (They're resized with CSS, so if you already have 140px or 168px logos, for example, that's fine.)

There are two database fields in the 'products' model currently: "image" and "alternate image." Use the "image" field. The second is no longer necessary, so optionally, I've removed that in this PR: https://github.com/mozilla/kitsune/pull/4176

@akatsoulas I put it in a separate branch with a new PR because it's just a clean-up issue, and there may be other backend consequences that I'm unaware of for removing it.

**Comment by jess-cook03** [comment]
@akatsoulas are we able to make this change?? per @kkellydesign comments above? I would say that it is a bit of a priority as these cards are used heavily across the site.

**Comment by jess-cook03** [comment]
@kkellydesign can you inform me what the content needed tag is for? Are we saying the the logo assets?

**Comment by kkellydesign** [comment]
On my local database, this URL: 
http://localhost:3000/admin/products/product/2/change/

<img width="840" alt="Screen Shot 2020-02-28 at 12 52 43 PM" src="https://user-images.githubusercontent.com/202590/75572750-61d92080-5a29-11ea-8e6f-4459ce11a736.png">

I added this image: 
![2020-02-13-06-18-50-f471f2](https://user-images.githubusercontent.com/202590/75572891-ac5a9d00-5a29-11ea-9c16-2767fd60f186.png)

and get this result: 
<img width="457" alt="Screen Shot 2020-02-28 at 12 56 47 PM" src="https://user-images.githubusercontent.com/202590/75572957-d4e29700-5a29-11ea-8864-ad02db94c22e.png">
<img width="332" alt="Screen Shot 2020-02-28 at 12 56 54 PM" src="https://user-images.githubusercontent.com/202590/75572958-d4e29700-5a29-11ea-9dd6-452d01d271ea.png">

**Comment by akatsoulas** [comment]
@jess-cook03 what change should that be?

**Comment by jess-cook03** [comment]
@akatsoulas @LeoMcA @kkellydesign 
ALL LOGO ASSETS:
[SUMO_Product Logo Assets.zip](https://github.com/mozilla/sumo-project/files/4394038/SUMO_Product.Logo.Assets.zip)

**Comment by jess-cook03** [comment]
PNGs only: 
[SUMO_Product Logo PNGs.zip](https://github.com/mozilla/sumo-project/files/4394635/SUMO_Product.Logo.PNGs.zip)
