### ISSUE TITLE
[New messages] The dimensions of the users drop-down don't match the dimensions of the To: search box.

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo-project#175]
STR:

1. Go to https://test.sumo.mozit.cloud/en-US/messages/new
2. In the To: field type something, ex. kasey 

Observe the drop-down box.
 
ER: The dimensions of the drop-down should match the dimensions of the To: search box. 
AR: The dimensions of the drop-down don't match the dimensions of the To: search box. 

Print screen with the actual result: https://imgur.com/a/f7Y7IGO

**Comment by kkellydesign** [comment]
I made a couple of minor adjustments that improved this somewhat, but I'm limited because the javascript plugin is calculating the width on runtime. This is an improvement, so I think it's safe to close. 

This will go up with https://github.com/mozilla/kitsune/pull/4190

<img width="953" alt="Screen Shot 2020-02-25 at 5 31 14 PM" src="https://user-images.githubusercontent.com/202590/75293913-34a42c80-57f5-11ea-91fc-251ef74aee1a.png">

**Comment by kkellydesign** [comment]
This is ready for testing: 
https://test.sumo.mozit.cloud/en-US/messages/new
<img width="952" alt="Screen Shot 2020-02-26 at 11 36 48 AM" src="https://user-images.githubusercontent.com/202590/75366218-63b9ad00-588c-11ea-91d8-24895555dfff.png">

**Comment by ovidiuboca1** [comment]
Tested on desktop (OS X 10.14, Windows 10) and mobile/tablet (iPad, iPhone 8 plus, Huawei p20) and I can confirm the fix.
