### ISSUE TITLE
Article Discussions / Page Template broken UI?

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#237]
https://test.sumo.mozit.cloud/en-US/kb/containers/discuss/7459#post-18359

These pages .... the best advice I have would be if we could apply the **forum template styling** to these pages.... I don't know if thats possible?

And if we cant do that (apply the forum styling template here) then..
I guess minimally I would say:

- [ ] text block that says 'open links in new tabs...' make it grey and remove/override the huge heading styles ... use body LG (18px) bold

- [ ] add dividing lines between each users reply ( grey lines like the forum)

- [ ] align the buttons (private message) to the right hand side along with the edit links and delete links

@madasan @akatsoulas for now I marked as blocks release -- only depending on much this page is used or if we feel its of priority, lets discuss in the morining.

**Comment by kkellydesign** [comment]
I've just applied all of the forum markup to these templates so I'm 99% sure this will be good in https://github.com/mozilla/kitsune/pull/4224. However, my database doesn't have the URL posted above, and I can't figure out how to create a post that uses these templates, so I made the changes blind. So lets merge in this PR and see how it looks... and if it's still off then I'll need a hand to recreate the problem locally.

**Comment by ovidiuboca1** [comment]
@jess-cook03 @kkellydesign I'm still seeing the huge text for example.

**Comment by kkellydesign** [comment]
big text is fixed: https://github.com/mozilla/kitsune/pull/4232

The {for win} tags are still in there, but I assume that's the case on production as well, because the forum discussions aren't parsed through the same markup language that the document is. This is the expected behavior, because the discussion is about the content of the article between authors who are familiar with this format. 

<img width="1036" alt="Screen Shot 2020-03-16 at 10 17 11 AM" src="https://user-images.githubusercontent.com/202590/76767900-aaeedb80-6770-11ea-9568-0417de68f169.png">

**Comment by ovidiuboca1** [comment]
I verified this on desktop (Mac OS X 10.14) and mobile device (iPhone 8 plus) and I can confirm that the text font is fixed. 
@jess-cook03 I will move this but if you think that this is not done, please comment.
