### ISSUE TITLE
Weird scroll behaviour on mobile with hamburger menu

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#273]
As described on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1623781

@kkellydesign have you got any idea what might be causing this?

**Comment by kkellydesign** [comment]
This is fixed here: https://github.com/mozilla/kitsune/pull/4246

**Comment by kkellydesign** [comment]
@LeoMcA I had applied a reset function to close the navigation when the window is resized, either on desktop or mobile. The desktop and mobile behaviors are very different, so this was a way to clear everything out. The issue was that when you scroll on mobile, the browser UI for the toolbars shrink out of the way, which changes the height of the viewport. The couple of commits that fix this change the function so that it only checks for a viewport change on the width, not the height.

**Comment by LeoMcA** [comment]
Ah, very nice catch there!

**Comment by ovidiuboca1** [comment]
I verified this on iPhone 8 plus and I can confirm the fix.
