### ISSUE TITLE
AAQ Step 4 backend: progress bar needed on final question URL

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#288]
When the question is submitted, you're redirected to the new question page URL that you've just created, with an alert message that mentions the successful submission. In addition to that message, we need to show the progress bar on that page. If the page is refreshed or visited from another page, the progress bar should not appear. 

I've put the markup in the correct place and tested it, so all of the states are working correctly. I commented it out though, because it needs some sort of conditional to only appear in this particular scenario. Here's the line that needs un-commented and fixed: 

https://github.com/lincolnloop/kitsune/commit/498838ec9ff8547e0c518d8b06074134d7f9db37#diff-c974612e16a151dc4a46a3782b8298e2R33

**Comment by LeoMcA** [comment]
As discussed in today's design review, I need to update the progress bar to not link anywhere on this step, and adjust the message to include a link to "My Questions" as shown in the prototype: https://mozilla.invisionapp.com/share/QSWDARJJRDT#/screens/410503889

**Comment by ovidiuboca1** [comment]
This issue was tested on dev environment with Firefox 76 and Chrome 81 on Mac OS X 10.14, Windows 10, mobile devices iOS and Android and I can confirm the fix, the user is redirected to the new question, the progress bar is there and also the alert message. If the page is refreshed or is visited from another page the progress bar is not displayed.
