### ISSUE TITLE
Responsive Redesign // Subproduct Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#30]

**Comment by kkellydesign** [comment]
https://test.sumo.mozit.cloud/en-US/products/firefox

This is ready for QA, with some exceptions. Static files are still not loading, which means: 
* Fonts are using the sans-serif fallback instead of Inter and Metropolis. 
* The masthead photo is displaying the alt tag for the broken image instead of the logo. Here's what that looks like for me locally, where the fallback image is working correctly. To be clear, that's what happens when there's an empty field in the database, not a broken link. When the staticfiles works, it should populate the actual firefox logo in this spot. 
<img width="525" alt="Screen Shot 2020-01-24 at 3 02 07 PM" src="https://user-images.githubusercontent.com/202590/73100095-dbc23b00-3eba-11ea-9ad5-4759a99f274e.png">
* Icons under 'frequent topics' and 'featured articles' are both missing. 
* The close button on notifications is missing. 

Additional notes: 
In an upcoming PR, the search on this page will work identically to the homepage. It's functional now, but the layout is a bit off. The icons on search results are also related to the staticfiles issue.

**Comment by ovidiuboca1** [comment]
Comparing the dev environment and the staging one related to the sub-products pages I see different behavior. On https://test.sumo.mozit.cloud/en-US/ I don't see any sub-product pages. I did a screen recording where I compared the dev environment, where the sub-product pages exist and the test environment where I don't see any sub-product pages: https://streamable.com/nhoqt

**Comment by kkellydesign** [comment]
I believe this is either an issue with data differences, or subproducts not being implemented yet in the responsive-redesign branch. @akatsoulas, can you confirm?
