### ISSUE TITLE
 No images are displayed when you preview an article

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#346]
see https://bugzilla.mozilla.org/show_bug.cgi?id=1630056

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4308

**Comment by ovidiuboca1** [comment]
I tested that on desktop and I can confirm the fix.
On mobile the issue is still reproducible, the image is not displayed and also the text preview is not displayed correctly. On a mobile device -  Go to https://support.allizom.org/ro/kb/change-your-default-search-settings-firefox/translate?discard=%C3%8Enl%C4%83tur%C4%83#preview and preview the article.  
CC @kkellydesign, @akatsoulas

**Comment by LeoMcA** [comment]
The padding is all messed up on mobile, but the images do display for me, so I think this needs to be filed as a separate issue.

However, I do need to work on this issue a little more because my fix broke previewing outside the KB where the `lazyload` helper isn't loaded.

**Comment by ovidiuboca1** [comment]
For the mobile padding, I filed issue https://github.com/mozilla/sumo-project/issues/366
I still don't see the image on mobile, the mobile device that I use is the iPhone 8 plus.

**Comment by kkellydesign** [comment]
CSS issues mentioned in this ticket are fixed. See comment here: https://github.com/mozilla/sumo-project/issues/366#issuecomment-614661969

**Comment by ovidiuboca1** [comment]
I tested this and I can confirm the fix, also on mobile I can see the uploaded picture.
