### ISSUE TITLE
Toggle syntax hightlighting is not working when translating an article

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#361]

**Comment by LeoMcA** [comment]
In fact, toggle syntax highlighting also doesn't work when editing an article, the root cause seems to be the [`toggle()` event handler](https://api.jquery.com/toggle-event/) was removed from jQuery (but not the [other `toggle()`](https://api.jquery.com/toggle/)).

There seems to be one or two other places using that removed `toggle()` - I'll fix them as well.

**Comment by LeoMcA** [comment]
So these broken toggles appear in a few places:
* Edit KB article, eg: https://support.allizom.org/en-US/kb/get-started-firefox-overview-main-features/edit
* Edit KB translation, eg: https://support.allizom.org/ga-IE/kb/a%20fh%C3%A1il-%20thosaigh%20-%20firefox%20-%20forbhreathn%C3%BA%20-%20pr%C3%ADomh%20-%20gn%C3%A9ithe/edit
* Common responses modal (there should be a button which switches between editing and previewing the response), eg: https://support.allizom.org/en-US/questions/1207033 (click on "Common Responses" in the "Post a Reply" toolbar.

This PR should fix them: https://github.com/mozilla/kitsune/pull/4311

**Comment by ovidiuboca1** [comment]
I verified this on desktop, Mac OS X 10.14 and Windows 10 with FF and chrome and I can confirm the fix.
Also tested on mobile and the issue is fixed.
