### ISSUE TITLE
Add "Guides" link in contributor Tools

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#388]
In the Contributor Tools menu in the nav, please add a link to https://support.mozilla.org/products/contributor with the string "Guides"

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/4346

**Comment by mirunacurtean** [comment]
Verified fixed in Stage. 
When opening link in same tab or in a new tab, from Contributor Tools or For Contributors links, it directs to https://support.mozilla.org/products/contributor, containing the additional language parameter, as expected. 
Verified on en-US, FR, AR, DE, ES and zh-CN. 
Tested across Firefox 75 release and Chrome 81 release version on the following platforms:
Mac OS X 10.14
iPhone 8 plus
Windows Pro 10 64-bit 
Android 8.0.0
![Guides link ](https://user-images.githubusercontent.com/53306802/81051514-74a91f00-8eca-11ea-9381-7ae5ea9f64ba.gif)
