### ISSUE TITLE
'Get Community Support' & community hidden topics

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#397]
How / where do we want to link to these pages? following the breadcrumbs is currently confusing.
Right now I understand we need to link to https://support.mozilla.org/en-US/kb/get-community-support for locales that don't have their own forums👍....  but what about all the rest of these pages for example: https://support.mozilla.org/en-US/products/firefox/support-forum https://support.mozilla.org/en-US/kb/forum-rules-and-guidelines ?

Hidden topics and hidden products?
Would like to gather some clarity around how these are living on the site right now, how users are navigating to them (or not) and then figure out what our future ideal state of these are? 
I mentioned these previously and spoke with @jonichan about them.... thinking we could hide them altogether, which I still think we should do somehow if we can. But right now I get the feeling that this is not possible?

This may be an overlap with the IA implementation and also the contributor onboarding project, but wanting to get this on the board regardless.

______________________
Besides these questions^ there are a few UI and language changes we can make to this page: https://support.mozilla.org/en-US/kb/get-community-support since we are going to link to this and we do currently.

- [ ] article title change to: 'Ask the Community'

- [ ] 'get help' green button --- remove this and replace with our blue primary button of "ask the community' (like how we have across the site)
![Screen Shot 2020-04-21 at 4 21 29 PM](https://user-images.githubusercontent.com/54991698/79910487-cfcc1380-83ec-11ea-9e7a-d1db01dc8756.png)

- [ ] sidebar -- what is happening here? i am logged in so I can see the editing tools, but would like to understand why there are so many dropdowns here, seems unusual compared to other articles ive seen. And with this the up/down vote then gets left hanging below? Seems odd.
![Screen Shot 2020-04-21 at 4 22 58 PM](https://user-images.githubusercontent.com/54991698/79910471-c93d9c00-83ec-11ea-9b55-e4886bf08117.png)

**Comment by LeoMcA** [comment]
> Right now I understand we need to link to https://support.mozilla.org/en-US/kb/get-community-support for locales that don't have their own forums

I think we should do this the other way round: rather than link to this page which then links to the AAQ flow, I think we should redirect users out of the AAQ flow to this page when we detect that they're trying to ask a question in a product forum in a locale which doesn't exist (so as the third step of the new AAQ).

We already do this detection, but the logic is a bit scattered around, and we redirect to the English language forum instead of this page (e.g: https://support.mozilla.org/fr/questions/new/desktop goes to en_US).

> what about all the rest of these pages for example: https://support.mozilla.org/en-US/products/firefox/support-forum https://support.mozilla.org/en-US/kb/forum-rules-and-guidelines

Both because my above proposal would remove the https://support.mozilla.org/en-US/kb/get-community-support for English locales and also because I think it's a better place for them anyway, I think these articles should be linked in the final step of the AAQ flow. So for instance have the "forum guidelines" linked under the compose box, and the "how to take a screenshot" one under the image upload section.

> sidebar -- what is happening here? i am logged in so I can see the editing tools, but would like to understand why there are so many dropdowns here, seems unusual compared to other articles ive seen.

This feels like it could be a bug in the showfor code, but it could also be all those products are associated with the article in the admin interface - for whatever reason I can't currently open the article in the admin interface to check, though.

**Comment by jess-cook03** [comment]
@jonichan 
Setting up time to review with you .

Next steps here:

- [ ] understand the goals of this page: https://support.mozilla.org/en-US/kb/get-community-support (how these are living on the site right now, how users are navigating to them (or not) and then figure out what our future ideal state of these are? do we need to redesign this page & its content? do we need a new page altogether?)

- [ ] Understand AAQ flow for locales that do not have their own product forums

**Comment by akatsoulas** [comment]
Closing this issue as stale
