### ISSUE TITLE
Blank banner showing up on support.mozilla.org

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo-project#4]
When I view support.mozilla.org, there's a light blue banner above the black header. It has no text but is dismissible with an "x". 

<img width="1275" alt="Screen Shot 2019-11-27 at 3 52 15 PM" src="https://user-images.githubusercontent.com/4714678/69758750-5a566280-112e-11ea-9424-75dd703f2d35.png">

**Comment by kkellydesign** [comment]
This is related to the geoip-locale.js error that we're seeing on production and on the testing environment. I'm not sure what why this is failiing, but I've at least made it fail a little more gracefully since this doesn't seem to be a mission-critical component. It now throws a console warning intstead of an error, and then removes the blank notification bar when the error is caught. [This commit](https://github.com/lincolnloop/kitsune/commit/bcac333e857469a747c01f3a510d1ea161b57094) will be in when https://github.com/mozilla/kitsune/pull/4130 goes live.

**Comment by kkellydesign** [comment]
I'm moving this to QA since what I have done here is an improvement. I'm not seeing anything on production at `/geoip-suggestion`, which is referenced here: 

https://github.com/lincolnloop/kitsune/blob/ac0f55958b62b466f568971bc91a5d05a298f35c/kitsune/sumo/static/sumo/js/geoip-locale.js#L56

I'm not sure how else to test this to see if it does anything in other locales or environments. If this script is truly not working, it can be removed entirely here, but I'm not comfortable making that call. 

https://github.com/lincolnloop/kitsune/blob/master/kitsune/bundles.py#L291
