### ISSUE TITLE
Drop sumo accoutns middleware

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#443]

**Comment by mirunacurtean** [comment]
@akatsoulas Could you confirm my understanding of this change? 
Despite the back-end changes the functionality of the accounts used in SUMO is supposed to be the same after this is deployed to stage. Would this apply to account creation from various entry points and also sign in? Should this be tested in order to verify this ticket?
What other acceptance criteria is there? Do we also have to take into different types of accounts, meaning accounts with different permission, like Staff? (I currently have no idea how set up one of those)
Does updating/editing the profile also count as something to be tested after this deploy?

**Comment by akatsoulas** [comment]
This change only targets the old SUMO accounts, not the accounts that are using FxA to login. Basically what this did was to deactivate any active sessions by logging out users who were using the old accounts. With this change I am just removing this functionality

**Comment by mirunacurtean** [comment]
Understood. Then this is not something that I can reproduce and or verify.
