### ISSUE TITLE
Account is not signed out after password change and password is not requested after logout/login

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo-project#452]
**Affected platforms:**
MacOS X 14.0
Windows 10 64-bit
Android 8.0.0

**Browsers**
Firefox
Chrome

**Environments**
Production 
Stage

**Precondition:** 
Create account and sign in.

**Steps to reproduce:**

1. On support.mozilla.org hover over the user avatar and select Edit Profile> manage Firefox Account.
2. On Manage account page scroll to Password section and select to Change it. Fill in valid old password and new password fields and click to update. 
3. Choose not to save the new password in the "save password message panel" when it shows during the process. 
4. Return to SUMO site and refresh the page. The account is not logged out, as expected, 
5. Sign out and sign back in.

**Expected results:**
1.When updating the password from Manage account page the account should be signed out when returning to sumo site, at least after refresh or when navigating the site or opening a new tab, 
2. When signing out and back in on the site and the new password has not been saved in the browser, then the password should be requested in the sign in flow. 

**Actual Results:**
Account is not logged out from SUMO after changing password and after signing out and back in no password is requested in the sign in flow. 

![Account is not signed out after password change](https://user-images.githubusercontent.com/53306802/83538759-e478ec80-a4fe-11ea-9f32-f3cc8628ca8f.gif)

NOTE: After clearing browsing data from the browser on Windows, the account is logged out and the password is requested in the sign in flow.

**Comment by LeoMcA** [comment]
@mirunacurtean this is a fantastic report, thank you. There's a few pieces to break down:

> 1.When updating the password from Manage account page the account should be signed out when returning to sumo site, at least after refresh or when navigating the site or opening a new tab,

This is true, and should have been happening on staging, but likely wasn't because of the job backlog. It should be happening on staging now.

> 2. When signing out and back in on the site and the new password has not been saved in the browser, then the password should be requested in the sign in flow.

This piece is out of our control, since Firefox Accounts decides when to prompt the user for a password.

However, technically it is the "correct" behaviour from Firefox Accounts - although from a user perspective it seems wrong: why is SUMO logging me out on password change, when Firefox Accounts keeps me logged in?

I imagine what's happening is Firefox Accounts keeps track of what session was used to change the user's password, and only logs the user out of all other sessions. There's no need to get a user to log in again with their new password if they've just entered it.

However, there's no way (currently) for SUMO to know which Firefox Accounts session was used to change the password, nor is there a way (currently) for SUMO to associate that Firefox Accounts session with a SUMO session, and log the user out of all sessions but that one.

So the only option for SUMO is to log a user out of all sessions started before the password change happened on Firefox Accounts.

Hopefully that explains the inconsistency between Firefox Accounts and SUMO session handling.

So, with the technical constraints we currently have, the expected behaviour is:
> after signing out and back in no password is requested in the sign in flow.

**Comment by mirunacurtean** [comment]
@LeoMcA Very glad to know the format and the details given in the report have been helpful. 
Thanks as well for the detailed explanation on the relation of Firefox Accounts versus SUMO session and providing a clear expected behavior. 
Taking that into consideration I've tested this again in stage and it works as intended:
- When navigating through the site, or refreshing the page or opening a new SUMO tab the account is logged out. 
- Tested between mac, windows and an android mobile device as well and can confirm that account is logged out of the other devices as well when performing any of the actions described above. 
- Tested on Firefox, Chrome and Safari browsers. 

As for requesting the password after it has been changed on a new sign in, that also occurs as expected, but I'm writing it down as a "good to have" if it gets approved. 

As it is, I'm closing this ticket as it's been verified and working as expected.

**Comment by LeoMcA** [comment]
Hmm, this is bizarre, my only thought is that there could be a delay on the logout which we're not seeing because of clearing the data.

Can you run a test like the following:

1. Log in on the misbehaving device
2. Log in on another device with the same account
3. Change the password on that Firefox Account
4. Refresh the device in step 2 until you're logged out
5. Refresh the device in step 1

Then the device in step 1 should be logged out, if not try refreshing again.

**Comment by mirunacurtean** [comment]
We tried that between the two mac devices I mentioned before since on one of them the logout issue did not occur.  

The exact steps were:
1. Login on macOS 10.14 with mozillatest1234@yahoo.com. 
2. Login on macOS Mojave 10.14.6 with the same account. 
3. Change password on device 1. 
4. Refresh page on device from step 2. 
3. Refresh page on device 1. 

Neither the device were logged out from the browser. This was unusual since on macOS Mojave 10.14.6 this was working  before so I performed a change password test on the same browser. same profile with another account, mcurtean4@mailinator.com, and this time I was signed out at page refresh. 
The previous day I'd also tested with other recently created test accounts and had not encountered the issue so is it possible that it's due to using mozillatest1234@yahoo.com that the signout does not occur?

**Comment by LeoMcA** [comment]
Ok, now this is interesting! We're haven't stored any any FxA notifications for the mozillatest1234@yahoo.com account... either FxA is sending them to us, and for some reason we're failing to store them, or FxA doesn't send notifications for this account (maybe because it has "test" in the name?).

Are you able to repeat the above test with the mcurtean4@mailinator.com email instead, because we are receiving and storing events for that account.

**Comment by mirunacurtean** [comment]
Yes. Just performed the test using mcurtean@mailinator,com and finally managed to log out on both devices at page refresh so it was definitely an account issue. 
It's strange that mozillatest1234@yahoo.com changes were not sending any notifications but this was an exception. Unless we're going to investigate that further, I think this issue can be closed now.

**Comment by LeoMcA** [comment]
Perfect! I've opened https://github.com/mozilla/sumo-project/issues/469 to track that issue down, but yes I agree this issue can be closed since the mailinator account worked.
