### ISSUE TITLE
Question/reply blocklist

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#476]
Expected behaviour in a gdoc (visible to all Mozilla staff), so as to avoid giving the scammers a playbook on how to defeat this: https://docs.google.com/document/d/10hqiP-by9cgf6ZkpdsGtlcs4hAXs_XmrGPjsuacLYWA/edit?usp=sharing

**Comment by mirunacurtean** [comment]
Confirmed to be working as expected on Desktop (Windows PRO 10 64-bit and macOS 10.14.6) on FF, Chrome and Safari and on Android 9.0 on FF and Chrome. 
Verified that when trying to post a question containing the block-listed number ( 1-833-605-1010, 18336051010, 108336051010) in the "How can we help?" section the user will be signed out and the question is not posted. 
The same result is obtained when trying to edit your own question or another user's (with a moderator account) in order to add or edit the phone number. verified question replies and question replies edit scenarios as well and in none of them is the block-listed number posted successfully. 
A different number, even if very similar, can be posted. 

@LeoMcA  One clarification is needed however - should we allow the number to be posted in the subject (see example https://support.allizom.org/en-US/questions/1207062) or is it an unlikely scenario?

**Comment by LeoMcA** [comment]
Closing since this is deployed, and #489 will change the behaviour quite a lot.
