### ISSUE TITLE
KeyError for non existing filter keys

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#550]
Manually setting a non existing sort order via the URL is causing a KeyError 500 error. This should be handled silently by defaulting to a sort order if the key is non existing.

**Comment by LeoMcA** [comment]
https://github.com/mozilla/kitsune/pull/4473

**Comment by mirunacurtean** [comment]
@akatsoulas 
After using existing sort order parameters I also used a non existing one, and no sorting results remained unchanged, although the "test" parameter was still a part of the URL.
Is this the expected behavior?
![Try these manual steps link](https://user-images.githubusercontent.com/53306802/88549183-ad1f4b80-d028-11ea-8efa-41410316c774.gif)

**Comment by akatsoulas** [comment]
If a non existing key is passed, it defaults to the `updated` sort order.

**Comment by mirunacurtean** [comment]
Changing a parameter and putting a non existing one in its place will results in the sorting returning to default section 'Attention Needed', Default sorting -'Updated' responses. Same applied for 'Filter By' and 'Show me' filtering.

![Defaulting to default section and default filter](https://user-images.githubusercontent.com/53306802/88553369-df7f7780-d02d-11ea-8e9d-f89a0af81ebb.gif)

Parameters within the URL are updated when new ones are selected from within the sumo page. 
![FF URL parameters updating depeonding on choice](https://user-images.githubusercontent.com/53306802/88554149-d2af5380-d02e-11ea-946b-c2c8e54dec19.gif)

Verified fixed on Windows 10, with Firefox and Chrome browsers.
