### ISSUE TITLE
Replace drop down fields in the admin interface for the users app with autocomplete.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#561]
Add also filtering capabilities for the AccountEvent entry in admin.

The rationale behind this change is that the pages in the admin that have FK are not rendered at all due to the many entries in the corresponding tables. Eg it's not possible to see an individual AccountEvent object.

**Comment by mirunacurtean** [comment]
@akatsoulas  Please provide and example of the expected behavior. I assume this is related to the Respond site administration page but does it apply to all categories or is it something else altogether?
![image](https://user-images.githubusercontent.com/53306802/89414509-2dcdfe00-d733-11ea-950c-680f05212eb5.png)

**Comment by akatsoulas** [comment]
This is for SUMO and not respond. If you navigate to the Account Events entry and you open a single entry, there will be a search box in the profile field

**Comment by mirunacurtean** [comment]
Confirmed that: 

1. In existing or "add account event" pages, when selecting the drop down menu a search box will show with an auto-populated menu of user profiles to pick from. 
2. When selecting the drop down menu, the search box search field's margins are highlighted and the cursor is set at the start of the field. 
3. Scrolling down in the results menu will "load more results" as the temporary info message announces. 
4. Selecting a result will close the search box and populate the Profile field with the chosen user profile. 

Possible improvements: 
1. Could the search results in an alphabetical order by default and also when a search is performed?
2. Searching for a user in particular will temporarily yield a " The results could not be loaded" response that appears to be 'broken' from the Profile field, before the search menu is again populated (see attachment),  Could this be because of stage delays? If not, could this be improved? @akatsoulas 

![Profile search box results](https://user-images.githubusercontent.com/53306802/89426365-c324be80-d742-11ea-8379-709be24e445d.gif)

**Comment by akatsoulas** [comment]
1. Yes it should but since this is offering a search field and it narrows down the results as you type, my preference would be not to invest any more time on this.
2. This is shown while the XHR request populates the results. Again I believe we can override the message with something else like `loading` but I am not sure if we should invest time for this nuance. If this was public facing I believe it would make sense to do both improvements. The access to admin is limited to a handful of employees only.

**Comment by mirunacurtean** [comment]
Alright, that makes sense. As it is operational I'm tagging it as Ready for Release.
