### ISSUE TITLE
Responsive Redesign // Translate navigation to new style system

### ISSUE THREAD

**Issue by kkellydesign** [mozilla/sumo-project#63]
This will be done in the styleguide first, and then when it's finished I'll work it into the templates. 

@madasan Please assign me and add this to the current sprint column.

**Comment by kkellydesign** [comment]
Lorem Ipsum text in the navigation menu needs to be replaced, and some URLs need to be added.

**Comment by kkellydesign** [comment]
Nav is ready for design QA, but is still missing a lot of URLs and there is filler text in the nav. @akatsoulas, I can hard-code URLs to the pages from the production site (most of the products don't exist in my DB), but the links that ported directly from the production site uses a lot of `{% url..` tags, so I'm not sure if hard-coding links is the best approach.

**Comment by jess-cook03** [comment]
@jonichan adding on this ticket also -- to monitor the navigation from copy perspective

**Comment by jonichan** [comment]
We'll need a section for Firefox Private Network too with the following list:
- Browser protection
- Desktop protection

The list will need to be updated as we launch other devices.

**Comment by kkellydesign** [comment]
I just added the two links listed above under the "firefox accounts" items. See screenshot below – @jess-cook03, if you have other ideas, let me know... we don't really have room to squeeze another column in here on anything other than the largest breakpoint. 

I have them going to the following pages – please double-check that these URLs are correct.

https://support.mozilla.org/en-US/products/firefox-private-network-vpn
https://support.mozilla.org/en-US/products/firefox-private-network

**Comment by kkellydesign** [comment]
These can now be seen in the footer here: https://test.sumo.mozit.cloud/en-US/

@jess-cook03, can you confirm this works for the design?

**Comment by jess-cook03** [comment]
@kkellydesign this is fine for now, but may need to be removed once reviewed by marketing -- I don't typically think this footer structure should allow for an extra section like that but its okay for now.
That being said we have the links bringing folks to the support pages for both browser level and device level... I am not sure if we need these links in the footer considering they can select those products above? @jonichan could this be an opportunity to link out to [the marketing site](https://fpn.firefox.com/) for users to learn more? And have this be the one link in the footer instead of 2?

**Comment by jess-cook03** [comment]
UI comment on footer @kkellydesign :
Headings here should be Inter not Metropolis
![Screen Shot 2020-02-18 at 4 31 52 PM](https://user-images.githubusercontent.com/54991698/74852643-dfef4600-530a-11ea-9b6f-8c36e834e43c.png)

**Comment by jess-cook03** [comment]
@jonichan Im connecting [this ticket ](https://github.com/mozilla/sumo-project/issues/28) for the contributor pages with the navigation comments here.

- [ ] select links that we want to have in the nav menu for the contributor side of the site -- For both the discussion section and the tools section of the menu. Items are currently marked with (remove)

- [ ] can choose from any of the listed contributor pages that are reskinned

**Comment by jess-cook03** [comment]
Connecting ticket #121 
Reference if needed @jonichan @kkellydesign

**Comment by kkellydesign** [comment]
Font is fixed here: https://github.com/mozilla/kitsune/pull/4182

**Comment by jonichan** [comment]
> @jonichan Im connecting #28 [this ticket ](https://github.com/mozilla/sumo-project/issues/28) for the contributor pages with the navigation comments here.
> 
>     * [ ]  select links that we want to have in the nav menu for the contributor side of the site -- For both the discussion section and the tools section of the menu. Items are currently marked with (remove)
> 
>     * [ ]  can choose from any of the listed contributor pages that are reskinned

Pages to be reskinned with Mozilla branding (in order of priority - based on usefulness)
*Get involved page: https://support.mozilla.org/en-US/getinvolved - most important
*Community Hub: https://support.mozilla.org/en-US/community
-----Ideal but not super important-------
**Profile documents page (ex https://support.mozilla.org/en-US/user/madasan/documents)
**Contributor forums page: https://support.mozilla.org/en-US/forums
**Recent Revisions page: https://support.mozilla.org/en-US/kb/revisions 
**KB dashboard: https://support.mozilla.org/en-US/contributors/kb-overview?product=
**Groups page: https://test.sumo.mozit.cloud/en-US/groups (so this isn't actually used right now because very few people knew it existed. But it would good to surface in the nav.

Additional pages to surface in the nav (in addition to what's in the IA):
*Groups page:https://support.mozilla.org/en-US/groups (under Tools)
*Moderate forum content: https://support.mozilla.org/en-US/flagged
*Community Hub (https://support.mozilla.org/en-US/community)

**Comment by jonichan** [comment]
> @kkellydesign this is fine for now, but may need to be removed once reviewed by marketing -- I don't typically think this footer structure should allow for an extra section like that but its okay for now.
> That being said we have the links bringing folks to the support pages for both browser level and device level... I am not sure if we need these links in the footer considering they can select those products above? @jonichan could this be an opportunity to link out to [the marketing site](https://fpn.firefox.com/) for users to learn more? And have this be the one link in the footer instead of 2?

One link is fine. We can call it Firefox Private Network and link it to https://fpn.firefox.com/

**Comment by kkellydesign** [comment]
@jonichan @jess-cook03 If we’re down to one link for the footer for FPN, we don’t need a headline. What do you think of this?
<img width="969" alt="Screen Shot 2020-02-20 at 10 03 25 AM" src="https://user-images.githubusercontent.com/202590/74947322-ab41c400-53c8-11ea-9c2a-b5314e4bf74f.png">

**Comment by jess-cook03** [comment]
@kkellydesign let me confirm re:
@jonichan could we put this link under one of the existing sections? Either Firefox Accounts or Firefox?
It looks odd just standing alone. If we want it to stand alone then I think it would need to be bold type and hover with underline ? which is not what the other headlines here do, so ideally can we group it with somethin

**Comment by jonichan** [comment]
> @kkellydesign let me confirm re:
> @jonichan could we put this link under one of the existing sections? Either Firefox Accounts or Firefox?
> It looks odd just standing alone. If we want it to stand alone then I think it would need to be bold type and hover with underline ? which is not what the other headlines here do, so ideally can we group it with somethin

Grouping it with Firefox Accounts could work, although it's not my preferred choice since it's not consistent with Benefits and Sign Up. We would also have to list all the Accounts products if we go with this option so users don't think FPN is the only Firefox Accounts offering.

I would go with @jess-cook03 's second suggestion: bold and underline on hover (or whatever styling you suggest to make it look like its own thing).

**Comment by jess-cook03** [comment]
@kkellydesign lets roll with that second option mentioned -- treating it like a bold header, stand alone and on hover it gets an underline. And link it to: https://fpn.firefox.com/

**Comment by jess-cook03** [comment]
This is all set
