### ISSUE TITLE
Set up synonyms on ES7

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#721]
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-synonym-tokenfilter.html

**Comment by mirunacurtean** [comment]
So far results for the following and only on English locale:
1. For more 'classical' examples I've tested 'disable cookies" versus "Block cookies" and the search results were identical and relevant for both cases. 
![Synonyms disable vs block](https://user-images.githubusercontent.com/53306802/110146439-409cd400-7de3-11eb-924f-8e769d09b7ab.gif)

2. Using the popular searches "addon". "add-on", "addons", "extensions" or "themes" returns the same results. 

![Synonyms addons extensions and themes](https://user-images.githubusercontent.com/53306802/110147205-0f70d380-7de4-11eb-9dce-0a3bdda5bcb2.gif)

**Comment by mirunacurtean** [comment]
@LeoMcA I was expecting the same examples "add-ons". "extensions", "themes" to be set as synonyms on other locales too, but in the tests performed on German locale, the results that contain their synonyms seem to be brought up only because of how frequent the search word is found in the company of these other words. 
When searching for "extension" and then "theme" in the same product category, different results are found and ranked as more relevant. 
![image](https://user-images.githubusercontent.com/53306802/110455045-a1245d80-80d0-11eb-8a10-b83ea2a05477.png)
![image](https://user-images.githubusercontent.com/53306802/110455078-aa152f00-80d0-11eb-9d47-c66bf96aa240.png)

**Comment by LeoMcA** [comment]
We have the ability to, but haven't set up any non en-US locale-specific synonyms, because we'll need input from localisers. However, these synonyms should be set up across all locales: https://github.com/mozilla/kitsune/blob/master/kitsune/search/dictionaries/synonyms/_all.txt

**Comment by mirunacurtean** [comment]
Re-tested using https://github.com/mozilla/kitsune/blob/master/kitsune/search/dictionaries/synonyms/en-US.txt examples from each category after reindexing was preformed and they all delivered results contains synonyms as well. 

![image](https://user-images.githubusercontent.com/53306802/110960263-3cc6ff80-8357-11eb-8c9f-43eabb923092.png)
![image](https://user-images.githubusercontent.com/53306802/110960677-acd58580-8357-11eb-933e-18c84a637153.png)
![image](https://user-images.githubusercontent.com/53306802/110961523-91b74580-8358-11eb-8aa3-41c461e6cf82.png)
