### ISSUE TITLE
Make sure unreviewed data in KB don't end up in Elastic

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#723]

**Comment by akatsoulas** [comment]
This also includes archived data too

**Comment by LeoMcA** [comment]
> This also includes archived data too

Archived data needs different treatment (and therefore a different issue, IMO), since now-archived data may have been in Elastic already, and then we have to decide what to do with what's already in there.

However, once this issue is closed, there will never be data in ES which then becomes unreviewed and has to be dealt with.

**Comment by mirunacurtean** [comment]
Looks good to me now on frontend. Verified it through re-testing https://github.com/mozilla/sumo-project/issues/731 but also submitting new content and updating articles, and only the approved changes were pulled upon in search results. 
For example https://support.allizom.org/en-US/kb/redirect-issue contains unreviewed content or https://support.allizom.org/es/kb/redireccion-%20problema and unreviewed summary which do not show up in search or searching using keywords from the unreviewed content does not bring up the documents in search results.
