### ISSUE TITLE
Generic approach for conditionally removing documents from indices

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#736]
Data being deleted from the DB is a simple case and is already handled using post_delete signals. This covers when a change in the DB means we no longer want data in ES which already exists there.

This might be used in a few places, such as:
* removing old AAQ documents we no longer want in ES
* removing WikiDocuments which are now redirects
* removing AAQ documents which have been marked as spam
* removing anonymized users

**Comment by akatsoulas** [comment]
I took a stub at this at the preliminary results are promising. Basically each prepare method is injecting an ad-hoc attribute, `es_discard_doc`. If this article is present the `to_action` method returns. Before doing so it also deletes the document in case it's already present in the index. The upside is that each prepare method can have its requirements about what to discard and does not require any additional changes. 

Moreover, I am looking into the possibility of simplifying the signals since each document type will be aware of the docs it needs to index/delete. PR will follow soon

**Comment by akatsoulas** [comment]
POC: https://github.com/mozilla/kitsune/pull/4649
The PR can be optimized further and include small improvements but I am keeping it to a minimum to further discuss this approach.

**Comment by mirunacurtean** [comment]
> Data being deleted from the DB is a simple case and is already handled using post_delete signals. This covers when a change in the DB means we no longer want data in ES which already exists there.
> 
> This might be used in a few places, such as:
> 
> * removing old AAQ documents we no longer want in ES

Verified through tests on archived data older than 2 years , as seen in https://github.com/mozilla/sumo-project/issues/740

> * removing WikiDocuments which are now redirects

Tested in https://github.com/mozilla/sumo-project/issues/705, https://github.com/mozilla/sumo-project/issues/723 and https://github.com/mozilla/sumo-project/issues/731

> * removing AAQ documents which have been marked as spam
> * removing anonymized users

Tested on the frontend though https://github.com/mozilla/sumo-project/issues/733 and also by deactivating a user account and marking all content as spam, questions and [answers](https://support.allizom.org/en-US/questions/1207044). 

![Remove anonimized user and spam question](https://user-images.githubusercontent.com/53306802/106637249-1d37fc80-658b-11eb-8f22-bf22143836fa.gif)
