### ISSUE TITLE
Receive notifications from FxA through webhooks.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo-project#76]
FxA will send notifications through a webhook that will inform sumo when there is a status change in the user's account.

**Comment by akatsoulas** [comment]
The following actions are supported:
* Deletions: When a Firefox Account is deleted, we invalidate the account in SUMO too.
* Subscription changes: When a subscription is updated, it's propagated to SUMO too.
* Password change in FxA: When a user updates the password in FxA, SUMO logs the user out.

**Comment by mirunacurtean** [comment]
Account is not logged out after password change in FxA so I've copied here the details from slack for more reference:
"About being signed out after changing the password or deleting the account - this does not happen immediately, in fact there are two different behaviors.
On Windows I am able to change the password, receive the email notification about but after I return to the site pages and refresh or navigate through sumo I am not logged out. however, on both FF and chrome, after I preform a CTRL+SHIFT+DEL to clear the last hour I am signed out - which means some caching issues are persisting in stage.
On Mac - on both Ff and Chrome, after changing the password and returning to SUMO the user is not logged out even after performing the Clear browsing data workaround or refreshing the page."

@akatsoulas  After further testing on production as well I've discovered that the same behavior occurs there as well and since it is not a regression but rather a separate issue which affects this one I've created a separate ticket for it. 
https://github.com/mozilla/sumo-project/issues/452

**Comment by LeoMcA** [comment]
> Account is not logged out after password change in FxA

This was likely because of the job backlog in staging, this should be cleared now.

> On Mac - on both Ff and Chrome, after changing the password and returning to SUMO the user is not logged out even after performing the Clear browsing data workaround or refreshing the page."

I'm not totally clued up on how the clear browsing data feature works, but were the sessions started within the hour on mac or well before? If there's an inconsistency here, let's file that as a separate issue.

**Comment by akatsoulas** [comment]
Closing this. We are seeing subscription change events coming through prod and being processed.
