### ISSUE TITLE
Use History API in Instant Search

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#776]
Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1643699

Far more times than I'm proud to admit I've tried to use the browser back button in instant search, and felt *very irritated* when it doesn't just exit me from instant search, but takes me to the page before the page I was searching on.

Technically this makes sense - we're just rendering instant search over the page the user was on - but it's a terrible experience.

At the very least, hitting back should just close instant search and reveal the page again (and then hitting forward again should take the user back to their search).

**Comment by mirunacurtean** [comment]
First off I wanted to discuss some behaviors that are probably not in the scope of this ticket, but could be considered for later on:
- should we think to enable return to a previously selected page of the search results through the back button?
- would it be useful to apply this for returning to a previous product category/ View All/Help Articles Only/ Community Discussion Only configuration?
- if we make an update to the search keywords after accessing any of the search results, should we get to see the first search query as well if we return far enough (using the back button)?
![search updated between queries](https://user-images.githubusercontent.com/53306802/109322970-990c2880-785b-11eb-901f-a4ca3a45e6dd.gif)

**Behaviors in the scope of this ticket:**
Return to search results (from a selected article or question thread) page through back button returns to the correct page/ selected section and product category and the keywords are typed in the search field.  This is in conformity with the expected result. 

However a short flash to the page where the search is performed, be that the homepage or in the AAQ forums that we could do without. Can this be improved?
![search back button](https://user-images.githubusercontent.com/53306802/109321831-48480000-785a-11eb-9320-68d2fb8105de.gif)

When the search input is erased and a new search phrase/keyword is typed in and the back button is pressed twice, the user is returned to the very first search, but there are no results. In this case the query should either be performed again at the return to that page in order to get the results, or the page should be skipped altogether. 

![return to previous search](https://user-images.githubusercontent.com/53306802/109322214-b12f7800-785a-11eb-8885-3dd78926099a.gif)

**Comment by LeoMcA** [comment]
> However a short flash to the page where the search is performed, be that the homepage or in the AAQ forums that we could do without. Can this be improved?

Nice catch! But not particularly easily. The flash happens because the url changes when clicking on a search result. So when you hit the back button, the browser is actually fully loading the previous (non search) page, and then renders the search on top, once that page is loaded. So going back from an article or question is the same behaviour as hitting refresh on an already loaded instant search results page (where you'll also see the flash).

There isn't a particularly neat solution to hiding it before its loaded, because all our javscript runs after the content has loaded.

Ultimately the solution will be to modify the URL when a user does an instant search. So, for example, searching for "firefox" would change the browser's URL to `support.mozilla.org/search?q=firefox` - the History API allows this without loading that page. But, then when a user navigates back to the search, or refreshes the search, the request would go to `support.mozilla.org/search?q=firefox`. There we'd need to render [the instant search server side](https://github.com/mozilla/sumo-project/issues/783), but there'd be no flash of content, because the search page is all that would be loaded.

**Comment by mirunacurtean** [comment]
Looks good to me now. Even when switching back and forth between search results using the browser button, the first and the last searches are being saved and the results listed. 

![searchception](https://user-images.githubusercontent.com/53306802/110478080-9c6da280-80ec-11eb-9077-7f66b2a60c4c.gif)

Other [tests ](https://docs.google.com/spreadsheets/d/1Vg6-nKpQeR7N_aBuW5RHSlpYJ3PIl0y-Hctu0HebweQ/edit?pli=1#gid=878209923&range=A14) were also successful.
