### ISSUE TITLE
FxA CTA Banner for Article Pages

### ISSUE THREAD

**Issue by jess-cook03** [mozilla/sumo-project#78]
Link to Miro for initial review/comments [https://miro.com/app/board/o9J_kwXHsgc=/](https://miro.com/app/board/o9J_kwXHsgc=/)

Link to preferred recommendations:  [ https://miro.com/app/board/o9J_kwWqXTE=/](https://miro.com/app/board/o9J_kwWqXTE=/)

**Comment by jess-cook03** [comment]
See ticket #174 
This has been implemented

**Comment by jess-cook03** [comment]
@madasan linking this google doc here with the copy/content options: https://docs.google.com/document/d/1-q4E9hbWd_Nx1EjJCQbgknsRM5x4tkCudrq7dqy-sSo/edit?usp=sharing

**Comment by jess-cook03** [comment]
@akatsoulas @LeoMcA @madasan @jonichan 
FxA Banner details:

- [ ] Main copy: Unlock more from the Firefox suite: Sync, Monitor, Lockwise, and more. 

- [ ] 'and more' will be treated as an inline text link w/ underline and link to: https://www.mozilla.org/firefox/accounts/

- [ ] button CTA 'Start Now' will link to: https://accounts.firefox.com

**Comment by jess-cook03** [comment]
@madasan @akatsoulas @jonichan 
Wanted to provide some updated visuals with the expected copy/content to help with the thoughts/decision around this for Wednesday. 
![Article_fxabanner01](https://user-images.githubusercontent.com/54991698/79160293-87d33e00-7da7-11ea-9b42-1194fad7e66d.png)
![Article_fxabanner02](https://user-images.githubusercontent.com/54991698/79160301-899d0180-7da7-11ea-9bd1-a512311a9ebe.png)

**Comment by jess-cook03** [comment]
Updates & decisions as of 04/15 ________

- Right now in the next release we will implement the 'in content' banner/ad within the articles content area ^ as shown above.

- Use the copy & links are listed above as they are still valid and should be used as is ^^ 

- [ ] An event to track the performance of this 'in content' banner is to be made and reviewed/assessed
_____________________________________________________
**Next steps:** 

- [ ] evaluate the performance of the 'in content' banner

- [ ] refine and work through solutions for a slim banner that solves the double cta/button issue and gives us a great option to use this instead going forward.... slim banner is preferred and makes more sense system wide, we need to create a design/copy solution that fits the needs.

- [ ] System components / define and refine this banner in relation to our current system announcement banners and then our inpage alert banners/messaging. 
How do we define these as different components within the same family?

**Comment by akatsoulas** [comment]
PR is opened here:
https://github.com/mozilla/kitsune/pull/4338

Once the finalized copy of the banner is review we can merge this and deploy it to prod.

**Comment by ovidiuboca1** [comment]
We can confirm the fix.
This issue was verified on staging with Firefox 75, chrome, safari, and edge using Mac OS X 10.14 and Windows 10. 
We used these URLs:

https://support.allizom.org/en-US/kb/access-your-add-ons-firefox-accounts
https://support.allizom.org/en-US/kb/im-having-problems-with-my-firefox-account
https://support.allizom.org/en-US/kb/change-your-firefox-accounts-password
https://support.allizom.org/en-US/kb/access-mozilla-services-firefox-accounts

**Comment by jess-cook03** [comment]
@akatsoulas some design tweaks:

- [ ] 4px border radius on corners

- [ ] break into 2 lines of text to allow for more spacing between content (see attached image)

- [ ] text - 'more.' please add underline and punctuation (.) change color to white like the rest of the text. Treatment should be the same as inline text link.

- [ ] icon size 36x36

- [ ] left and right padding increase to 32px

- [ ] top and bottom stays 24px

- [ ] padding/spacing outside the component in relation to other elements on the page increase to 48px top and bottom

Find the specs listed above here: https://www.figma.com/file/s8n4abacbaKQvBlk5Irqu0/Responsive-Redesign-Master-File-All-Pages?node-id=0%3A1

![Screen Shot 2020-05-05 at 1 34 47 PM](https://user-images.githubusercontent.com/54991698/81096982-349b6980-8ed5-11ea-9f87-c11482726346.png)

**Comment by akatsoulas** [comment]
@jess-cook03 the updated version is in staging. Example link:
https://support.allizom.org/en-US/kb/im-having-problems-with-my-firefox-account

The figma link returns a 404 for me so I couldn't get the specs from there. I tried to make it work based on the comments and the screenshot.

**Comment by ovidiuboca1** [comment]
We can confirm the fix. We compare actual results with the screenshot from this ticket. 
This issue was verified on staging with Firefox 75, chrome, safari, and edge using Mac OS X 10.14 and Windows 10.
We used the same URLs as before:

https://support.allizom.org/en-US/kb/access-your-add-ons-firefox-accounts
https://support.allizom.org/en-US/kb/im-having-problems-with-my-firefox-account
https://support.allizom.org/en-US/kb/change-your-firefox-accounts-password
https://support.allizom.org/en-US/kb/access-mozilla-services-firefox-accounts
