### ISSUE TITLE
username exists string isn't localized in zh-CN

### ISSUE THREAD

**Issue by LeoMcA** [mozilla/sumo-project#841]
https://github.com/mozilla-l10n/sumo-l10n/issues/45
https://bugzilla.mozilla.org/show_bug.cgi?id=1706539

**Comment by mirunacurtean** [comment]
Verified fixed in ES, FR, DE, IT, RO, zh-CN, AR, JA and pt-BR. 

![image](https://user-images.githubusercontent.com/53306802/120516057-a0514e00-c3d7-11eb-9b98-29566188c4b8.png)

![image](https://user-images.githubusercontent.com/53306802/120515931-8283e900-c3d7-11eb-926d-213ed5e411d4.png)

Tested using usernames with special characters as well. 
![image](https://user-images.githubusercontent.com/53306802/120517235-ebb82c00-c3d8-11eb-9282-8769a5a029b6.png)



Also checked that warning message for using other special characters than the ones allowed is also translated. 

![image](https://user-images.githubusercontent.com/53306802/120516243-d0005600-c3d7-11eb-8925-a7b18cc8fcf7.png)
